# Generated by Django 6.1 on 2026-09-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tenant_remove_user_tenant_id_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
