# Generated by Django 6.1 on 2026-09-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpverification_rate_limit'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='userrolepermission',
                    name='user_id',
                    field=models.IntegerField(),
                ),
            ]
        ),
    ]
