# Generated by Django 6.1 on 2026-08-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='subscriptions.subscription')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainers.trainer')),
            ],
        ),
    ]
